routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'admin'], function () {
    Route::resource('/users', 'UserController');
});
Route::get('/home', 'HomeController@index')->name('home');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    //    массив для записи
    protected $fillable = [
        'name', 'surname', 'midname', 'service', 'email', 'password',
    ];

    //    массив для скрытой записи
    protected $hidden = [
        'password', 'remember_token',
    ];

    //    массив атрибутов с наативным типом
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\User;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;

class UserController extends Controller
{
    //    отображение пользователей
    public function index()
    {
        $users = User::all();

        return view('admin.users.index', compact('users'));
    }

    //    отображение информации о выбранном пользователи
    public function show($id)
    {
        $user = User::find($id);

        return view('admin.users.show', compact('user'));
    }

    //    отображение страницы изменения пользователя
    public function edit($id)
    {
        $user = User::find($id);

        return view('admin.users.edit', compact('user'));
    }

    //    функция валлиодированния данных
    protected function validator(array $data)
    {
        return Validator::make($data, [
            'name' => ['required', 'string', 'max:50'],
            'surname' => ['required', 'string', 'max:50'],
            'midname' => ['required', 'string', 'max:50'],
            'service' => ['required', 'string', 'max: 500'],
            'email' => ['required', 'string', 'email', 'max:255'],
        ]);
    }

    //    изменение информации пользователя
    public function update(Request $request, $id)
    {
        $this->validator($request->all())->validate();

        $user = User::find($id);
        $user->name = $request->get('name');
        $user->surname = $request->get('surname');
        $user->midname = $request->get('midname');
        $user->service = $request->get('service');
        $user->email = $request->get('email');
        if ( !$request->get('password') == ''){
            $user->password = Hash::make($request->get('password'));
        }
        $user->save();

        return redirect()->route('users.index')->with('status', 'Запись успешно изменена');
    }

    //    удаление выбранного пользователя
    public function destroy($id)
    {
        User::find($id)->delete();

        return redirect()->back()->with('status', 'Запись успешно удалена');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;


class HomeController extends Controller
{
    // проверка роли авторизации
    public function __construct()
    {
        $this->middleware('auth');
    }

    // отображение главной страницы
    public function index()
    {
        return view('home');
    }
}

resources/views/admin/users/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">{{ __('Изменение учетной записи пользователя') }}: {{ $user->name }}</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif
                            <form method="POST" action="{{ route('users.update', $user->id) }}">
                                @method('PATCH')
                                @csrf

                                <div class="form-group row">
                                    <div class="col-4">
                                        <input id="name"
                                               type="text"
                                               name="name"
                                               placeholder="Имя"
                                               class="form-control @error('name') is-invalid @enderror"
                                               value="{{ $user->name }}"
                                               required
                                               autocomplete="name"
                                               autofocus
                                        >

                                        @error('name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>

                                    <div class="col-4">
                                        <input id="midname"
                                               type="text"
                                               name="midname"
                                               placeholder="Отчество"
                                               class="form-control @error('midname') is-invalid @enderror"
                                               value="{{ $user->midname }}"
                                               required
                                               autocomplete="midname"
                                               autofocus
                                        >

                                        @error('midname')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>

                                    <div class="col-4">
                                        <input id="surname"
                                               type="text"
                                               name="surname"
                                               placeholder="Фамилия"
                                               class="form-control @error('surname') is-invalid @enderror"
                                               value="{{ $user->surname }}"
                                               required
                                               autocomplete="surname"
                                               autofocus
                                        >

                                        @error('surname')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <div class="col-12">
                                        <input id="email"
                                               type="email"
                                               name="email"
                                               placeholder="Email"
                                               class="form-control @error('email') is-invalid @enderror"
                                               value="{{ $user->email }}"
                                               required autocomplete="email"
                                        >

                                        @error('email')
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <div class="col-12">
                                        <input id="service"
                                               type="text"
                                               name="service"
                                               placeholder="Заявка"
                                               class="form-control @error('service') is-invalid @enderror"
                                               value="{{ $user->service }}"
                                               required
                                        >

                                        @error('service')
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="form-group row">

                                    <div class="col-12">
                                        <input id="password"
                                               type="password"
                                               name="password"
                                               placeholder="Пароль"
                                               class="form-control @error('password') is-invalid @enderror"
                                               autocomplete="new-password"
                                        >

                                        @error('password')
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="form-group row mb-0 text-center">
                                    <div class="col-12">
                                        <button type="submit" class="btn btn-primary">
                                            {{ __('Изменить') }}
                                        </button>
                                    </div>
                                </div>
                            </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        @if(count($users) > 0)
                            {{ __('Пользователей:') }} {{ count($users) }}
                        @else
                            {{ __('Пользователей не обнаружено') }}
                        @endif
                    </div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <div class="table-responsive-xl">
                            <table id="example" class="table table-sm">

                                <thead>
                                <tr>
                                    <th scope="col">{{ __('#') }}</th>
                                    <th scope="col">{{ __('ФИО') }}</th>
                                    <th scope="col">{{ __('Почта') }}</th>
                                    <th scope="col">{{ __('Роль') }}</th>
                                    <th scope="col" >{{ __('Просмотреть') }}</th>
                                    <th scope="col">{{ __('Изменить') }}</th>
                                    <th scope="col">{{ __('Удалить') }}</th>
                                </tr>
                                </thead>

                                <tbody>
                                @if(count($users) > 0)
                                    @foreach($users as $user)
                                        <tr>
                                            <th scope="row">{{ $user->id }}</th>
                                            <td>{{ $user->surname }} {{ $user->name }} {{ $user->midname }}</td>
                                            <td>{{ $user->email }}</td>
                                            <td>
                                                @if($user->is_admin === 1)
                                                    {{ __('Администратор') }}
                                                @else
                                                    {{ __('Пользователь') }}
                                                @endif
                                            </td>
                                            <td>
                                                <a class="btn btn-block btn-sm btn-primary"
                                                   href="{{ route('users.show', $user->id) }}"
                                                >
                                                    {{ __('Просмотр')}}
                                                </a>
                                            </td>
                                            <td>
                                                @if(!($user->is_admin === 1))
                                                    <a class="btn btn-block btn-sm btn-primary"
                                                       href="{{ route('users.edit', $user->id) }}"
                                                    >
                                                        {{ __('Изменить') }}
                                                    </a>
                                                @endif
                                            </td>
                                            <td>
                                                @if(!(
                                                    (Auth::user()->id === $user->id)
                                                    ||
                                                    ($user->is_admin === 1)
                                                    )
                                                )
                                                    <form method="POST"
                                                          action="{{ route('users.destroy', $user->id) }}"
                                                    >
                                                    @method('DELETE')
                                                    @csrf
                                                        <button class="btn btn-block btn-sm btn-danger"
                                                                type="submit"
                                                        >{{ __('Удалить') }}</button>
                                                    </form>
                                                @endif
                                            </td>
                                        </tr>
                                    @endforeach
                                @else
                                    <tr>
                                        <td>Пользователей не существует</td>
                                    </tr>
                                @endif
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/users/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">{{ __('Информация пользователе') }}</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif
                        <p>{{ __('ФИО:') }} {{ $user->surname }} {{ $user->name }} {{ $user->midname }}</p>
                        <p>{{ __('Заказ:') }} {{ $user->service }}</p>
                        <p>{{ __('Почта:') }} {{ $user->email }}</p>
                        <p>{{ __('Дата регистрациия:') }} {{ $user->created_at }}</p>
                        <p>{{ __('Последние изменения профиля:') }} {{ $user->updated_at }}</p>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-12">
            <div class="card">
                <div class="card-header">{{ __('Главная страница') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <p>{{ __('Добро пожаловать,') }} {{ Auth::user()->surname }} {{ Auth::user()->name }} {{ Auth::user()->midname }}!</p>
                    <p>{{ __('Ваша почта:') }} {{ Auth::user()->email }}</p>
                    <p>{{ __('Ваш заказ:') }} {{ Auth::user()->service }}</p>
                    <p>{{ __('Ваш пароль:') }} {{ Auth::user()->password }}</p>
                    <p>{{ __('Дата Вашей регистрациия:') }} {{ Auth::user()->created_at }}</p>
                    <p>{{ __('Последние изменения профиля:') }} {{ Auth::user()->updated_at }}</p>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{ config('app.name', 'Laravel') }}</title>
    <script src="{{ asset('js/app.js') }}" defer></script>
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

</head>
<body>
<div id="app">
    <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
        <div class="container">
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('app.name', 'Laravel') }}
            </a>
            <button class="navbar-toggler"
                    type="button"
                    data-toggle="collapse"
                    data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false"
                    aria-label="{{ __('Меню') }}">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    @if (Route::has('login'))
                        @auth
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('home') }}">{{ __('Главная') }}</a>
                            </li>
                            @if(Auth::user()->is_admin === 1)
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('users.index') }}">{{ __('Пользователи') }}</a>
                                </li>
                            @endif
                        @endauth
                    @endif
                </ul>

                <ul class="navbar-nav ml-auto">
                    @guest
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Вход') }}</a>
                        </li>
                        @if (Route::has('register'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Регистрация') }}</a>
                            </li>
                        @endif
                    @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown"
                               class="nav-link dropdown-toggle"
                               href="#"
                               role="button"
                               data-toggle="dropdown"
                               aria-haspopup="true"
                               aria-expanded="false"
                               v-pre
                            >
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Выход') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    @endguest
                </ul>
            </div>
        </div>
    </nav>

    <main class="py-4">
        @yield('content')
    </main>
</div>

</body>
</html>